Esbarrado
BarefootTeam/EasyMarket-POO4 pull request #5
Opened 2017-11-12 00:12 UTC by LeoGitHubCosta

Cadastro de Valores

2017-11-12 18:12 UTC, LeoGitHubCosta commented
As Alterações que eu Fiz nesses commits São 👍 
 
💯 Valores CRUD. faltando Deletar

💯 Listagem das Compras e Detalhes de Cada Compra 

💯 Comecei a Verificar o Estoque tenho que melhorar algumas coisas ainda

2017-11-13 01:48 UTC, cemanuelio requested changes

2017-11-13 01:48 UTC, rodriguescelio commented on src/META-INF/persistence.xml
> +			<property name="hibernate.connection.url" value="jdbc:postgresql://localhost:5433/easymarket" />
E essa porta fora do padrão @LeoGitHubCosta ?

2017-11-13 15:53 UTC, cemanuelio approved these changes

2017-11-13 15:54 UTC, merged